/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* I2C_scl */
#define I2C_scl_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_scl_0_INBUF_ENABLED 1u
#define I2C_scl_0_INIT_DRIVESTATE 1u
#define I2C_scl_0_INIT_MUXSEL 19u
#define I2C_scl_0_INPUT_SYNC 2u
#define I2C_scl_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_scl_0_NUM 0u
#define I2C_scl_0_PORT GPIO_PRT6
#define I2C_scl_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_scl_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_scl_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_scl_INBUF_ENABLED 1u
#define I2C_scl_INIT_DRIVESTATE 1u
#define I2C_scl_INIT_MUXSEL 19u
#define I2C_scl_INPUT_SYNC 2u
#define I2C_scl_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_scl_NUM 0u
#define I2C_scl_PORT GPIO_PRT6
#define I2C_scl_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_scl_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* I2C_sda */
#define I2C_sda_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_sda_0_INBUF_ENABLED 1u
#define I2C_sda_0_INIT_DRIVESTATE 1u
#define I2C_sda_0_INIT_MUXSEL 19u
#define I2C_sda_0_INPUT_SYNC 2u
#define I2C_sda_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_sda_0_NUM 1u
#define I2C_sda_0_PORT GPIO_PRT6
#define I2C_sda_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_sda_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_sda_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_sda_INBUF_ENABLED 1u
#define I2C_sda_INIT_DRIVESTATE 1u
#define I2C_sda_INIT_MUXSEL 19u
#define I2C_sda_INPUT_SYNC 2u
#define I2C_sda_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_sda_NUM 1u
#define I2C_sda_PORT GPIO_PRT6
#define I2C_sda_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_sda_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Sns */
#define CapSense_Sns_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_0_INBUF_ENABLED 0u
#define CapSense_Sns_0_INIT_DRIVESTATE 1u
#define CapSense_Sns_0_INIT_MUXSEL 0u
#define CapSense_Sns_0_INPUT_SYNC 2u
#define CapSense_Sns_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_0_NUM 0u
#define CapSense_Sns_0_PORT GPIO_PRT9
#define CapSense_Sns_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_1_INBUF_ENABLED 0u
#define CapSense_Sns_1_INIT_DRIVESTATE 1u
#define CapSense_Sns_1_INIT_MUXSEL 0u
#define CapSense_Sns_1_INPUT_SYNC 2u
#define CapSense_Sns_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_1_NUM 1u
#define CapSense_Sns_1_PORT GPIO_PRT9
#define CapSense_Sns_1_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_2_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_2_INBUF_ENABLED 0u
#define CapSense_Sns_2_INIT_DRIVESTATE 1u
#define CapSense_Sns_2_INIT_MUXSEL 0u
#define CapSense_Sns_2_INPUT_SYNC 2u
#define CapSense_Sns_2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_2_NUM 2u
#define CapSense_Sns_2_PORT GPIO_PRT9
#define CapSense_Sns_2_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_3_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_3_INBUF_ENABLED 0u
#define CapSense_Sns_3_INIT_DRIVESTATE 1u
#define CapSense_Sns_3_INIT_MUXSEL 0u
#define CapSense_Sns_3_INPUT_SYNC 2u
#define CapSense_Sns_3_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_3_NUM 2u
#define CapSense_Sns_3_PORT GPIO_PRT10
#define CapSense_Sns_3_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_3_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_4_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_4_INBUF_ENABLED 0u
#define CapSense_Sns_4_INIT_DRIVESTATE 1u
#define CapSense_Sns_4_INIT_MUXSEL 0u
#define CapSense_Sns_4_INPUT_SYNC 2u
#define CapSense_Sns_4_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_4_NUM 4u
#define CapSense_Sns_4_PORT GPIO_PRT9
#define CapSense_Sns_4_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_4_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_5_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_5_INBUF_ENABLED 0u
#define CapSense_Sns_5_INIT_DRIVESTATE 1u
#define CapSense_Sns_5_INIT_MUXSEL 0u
#define CapSense_Sns_5_INPUT_SYNC 2u
#define CapSense_Sns_5_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_5_NUM 5u
#define CapSense_Sns_5_PORT GPIO_PRT9
#define CapSense_Sns_5_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_5_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_6_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_6_INBUF_ENABLED 0u
#define CapSense_Sns_6_INIT_DRIVESTATE 1u
#define CapSense_Sns_6_INIT_MUXSEL 0u
#define CapSense_Sns_6_INPUT_SYNC 2u
#define CapSense_Sns_6_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_6_NUM 6u
#define CapSense_Sns_6_PORT GPIO_PRT9
#define CapSense_Sns_6_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_6_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_7_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_7_INBUF_ENABLED 0u
#define CapSense_Sns_7_INIT_DRIVESTATE 1u
#define CapSense_Sns_7_INIT_MUXSEL 0u
#define CapSense_Sns_7_INPUT_SYNC 2u
#define CapSense_Sns_7_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_7_NUM 7u
#define CapSense_Sns_7_PORT GPIO_PRT9
#define CapSense_Sns_7_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_7_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_8_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_8_INBUF_ENABLED 0u
#define CapSense_Sns_8_INIT_DRIVESTATE 1u
#define CapSense_Sns_8_INIT_MUXSEL 0u
#define CapSense_Sns_8_INPUT_SYNC 2u
#define CapSense_Sns_8_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_8_NUM 0u
#define CapSense_Sns_8_PORT GPIO_PRT10
#define CapSense_Sns_8_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_8_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_9_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_9_INBUF_ENABLED 0u
#define CapSense_Sns_9_INIT_DRIVESTATE 1u
#define CapSense_Sns_9_INIT_MUXSEL 0u
#define CapSense_Sns_9_INPUT_SYNC 2u
#define CapSense_Sns_9_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_9_NUM 1u
#define CapSense_Sns_9_PORT GPIO_PRT10
#define CapSense_Sns_9_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_9_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Cmod */
#define CapSense_Cmod_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Cmod_0_INBUF_ENABLED 0u
#define CapSense_Cmod_0_INIT_DRIVESTATE 1u
#define CapSense_Cmod_0_INIT_MUXSEL 0u
#define CapSense_Cmod_0_INPUT_SYNC 2u
#define CapSense_Cmod_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Cmod_0_NUM 7u
#define CapSense_Cmod_0_PORT GPIO_PRT7
#define CapSense_Cmod_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Cmod_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Cmod_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Cmod_INBUF_ENABLED 0u
#define CapSense_Cmod_INIT_DRIVESTATE 1u
#define CapSense_Cmod_INIT_MUXSEL 0u
#define CapSense_Cmod_INPUT_SYNC 2u
#define CapSense_Cmod_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Cmod_NUM 7u
#define CapSense_Cmod_PORT GPIO_PRT7
#define CapSense_Cmod_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Cmod_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Uart_Printf_tx */
#define Uart_Printf_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Uart_Printf_tx_0_INBUF_ENABLED 0u
#define Uart_Printf_tx_0_INIT_DRIVESTATE 1u
#define Uart_Printf_tx_0_INIT_MUXSEL 18u
#define Uart_Printf_tx_0_INPUT_SYNC 2u
#define Uart_Printf_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Uart_Printf_tx_0_NUM 1u
#define Uart_Printf_tx_0_PORT GPIO_PRT5
#define Uart_Printf_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Uart_Printf_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Uart_Printf_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Uart_Printf_tx_INBUF_ENABLED 0u
#define Uart_Printf_tx_INIT_DRIVESTATE 1u
#define Uart_Printf_tx_INIT_MUXSEL 18u
#define Uart_Printf_tx_INPUT_SYNC 2u
#define Uart_Printf_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Uart_Printf_tx_NUM 1u
#define Uart_Printf_tx_PORT GPIO_PRT5
#define Uart_Printf_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define Uart_Printf_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
